name: C/C++ CI

on: [push, pull_request]
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      uses: actions/checkout@master
    - name: test and compile
      run: |
        for d in */ ; do
        cd "$d"
        make
        cd ..
        done
    - name: Upload
      uses: codecov/codecov-action@v1
