name: C1

on:
  push:
    branches: [ main ]
    paths:
      - 'lab1/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lab1/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab1 and test
      working-directory: ./lab1
      run: make
