name: C1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab1 and test
      working-directory: ./lab1
      run: make Makefile test
