name: C2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab2/task2.1.3 and test
      working-directory: ./lab2/task2.1.3
      run: |
        sudo apt install -y valgrind
        sudo pip install cpplint
        make
