name: C2

on:
  push:
    branches: [ main ]
    paths:
      - 'lab2/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'lab2/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab2/task2.1.3 and test
      working-directory: ./lab2/task2.1.3
      run: make Makefile
     - name: go to lab2/task2.2.6 and test
      working-directory: ./lab2/task2.2.6
      run: make Makefile
