name: C42

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to lab4/task4.2.7 and test
      working-directory: ./lab4/task4.2.7
      run: make
